export const cocktailMock = {
  idDrink: '11000',
  strDrink: 'Mojito',
  strDrinkAlternate: null,
  strTags: 'IBA,ContemporaryClassic,Alcoholic,USA,Asia,Vegan,Citrus,Brunch,Hangover,Mild',
  strVideo: null,
  strCategory: 'Cocktail',
  strIBA: 'Contemporary Classics',
  strAlcoholic: 'Alcoholic',
  strGlass: 'Highball glass',
  strInstructions:
    'Muddle mint leaves with sugar and lime juice. Add a splash of soda water and fill the glass with cracked ice. Pour the rum and top with soda water. Garnish and serve with straw.',
  strInstructionsES:
    'Mezcle las hojas de menta con el azcar y el zumo de lima. Aada un chorrito de soda y llene el vaso con hielo picado. Verter el ron y completar con soda. Decorar y servir con pajita.',
  strInstructionsDE:
    'Minzbltter mit Zucker und Limettensaft verrhren. Fge einen Spritzer Sodawasser hinzu und flle das Glas mit gebrochenem Eis. Den Rum eingieen und mit Sodawasser bergie en. Garnieren und mit einem Strohhalm servieren.',
  strInstructionsFR:
    "Mlanger les feuilles de menthe avec le sucre et le jus de citron vert. Ajoutez un filet d'eau gazeuse et remplissez le verre de glace concasse. Verser le rhum et complter avec de l'eau gazeuse. Dcorer et servir avec une paille.",
  strInstructionsIT:
    'Pestare le foglie di menta con lo zucchero e il succo di lime. Aggiungere una spruzzata di acqua di seltz e riempi il bicchiere con ghiaccio tritato. Versare il rum e riempire con acqua di seltz. Guarnire con una fetta di lime, servire con una cannuccia.',
  'strInstructionsZH-HANS': null,
  'strInstructionsZH-HANT': null,
  strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/metwgh1606770327.jpg',
  strIngredient1: 'Light rum',
  strIngredient2: 'Lime',
  strIngredient3: 'Sugar',
  strIngredient4: 'Mint',
  strIngredient5: 'Soda water',
  strIngredient6: null,
  strIngredient7: null,
  strIngredient8: null,
  strIngredient9: null,
  strIngredient10: null,
  strIngredient11: null,
  strIngredient12: null,
  strIngredient13: null,
  strIngredient14: null,
  strIngredient15: null,
  strMeasure1: '2-3 oz ',
  strMeasure2: 'Juice of 1 ',
  strMeasure3: '2 tsp ',
  strMeasure4: '2-4 ',
  strMeasure5: null,
  strMeasure6: null,
  strMeasure7: null,
  strMeasure8: null,
  strMeasure9: null,
  strMeasure10: null,
  strMeasure11: null,
  strMeasure12: null,
  strMeasure13: null,
  strMeasure14: null,
  strMeasure15: null,
  strImageSource: `https://pixabay.com/photos/cocktail-mojito-cocktail-recipe-5096281/`,
  strImageAttribution: `anilaha https://pixabay.com/users/anilaha-16242978/`,
  strCreativeCommonsConfirmed: 'Yes',
  dateModified: '2016-11-04 09:17:09',
};
